root = "."

[build]
  cmd = "go build -o cmd/hello-world/tmp/main ./cmd/hello-world"
  bin = "cmd/hello-world/tmp/main"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  follow_symlink = false
  log = "stdout"
  poll = false
  delay = 1000

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true
