# Dockerfile.prod.tmpl
FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod  ./
RUN go mod download
COPY . .
RUN go build -o hello-world ./cmd/hello-world

FROM scratch
WORKDIR /app
COPY --from=builder /app/hello-world ./hello-world
CMD ["./hello-world"]
