# Dockerfile.dev.tmpl
FROM golang:1.24-alpine AS dev

WORKDIR /app

# Instala dependências necessárias antes de copiar o código completo
# RUN go get github.com/stretchr/testify@v1.10.0
# RUN go get github.com/davecgh/go-spew

COPY . .

COPY go.mod   ./

RUN go mod tidy
# RUN go mod download

RUN go test -v ./...

RUN go install github.com/air-verse/air@latest
CMD ["/bin/sh", "-c", "go test -v ./... && air"]
