# Dockerfile.dev.tmpl
FROM golang:1.24-alpine AS dev
WORKDIR /app
COPY go.mod  ./

COPY . .
RUN go mod tidy
#RUN go mod download

RUN go test -v ./...

RUN go install github.com/air-verse/air@latest
CMD ["/bin/sh", "-c", "go test -v ./... && air"]
